[package]
name = "day11"
version = "0.1.0"
authors = ["Thorsten MÃ¼rell <thorsten@muerell.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
